### PR TITLE
docs: update roles and rights matrix

### PR DESCRIPTION
**Pull request by Phil91**
## Description

update roles and rights matrix

## Why

to have the latest roles and rights matrix available in the documentation

## Issue

N/A

## Corresponding Iam PR

https://github.com/eclipse-tractusx/portal-iam/pull/123

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [x] I have created and linked IP issues or requested their creation by a committer
- [x] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [x] I have added tests that prove my changes work
- [x] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by evegufy — CHANGES_REQUESTED** [review]
as part of https://github.com/eclipse-tractusx/portal-iam/issues/102, unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?

And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.

**Comment by jjeroch** [comment]
> as part of [eclipse-tractusx/portal-iam#102](https://github.com/eclipse-tractusx/portal-iam/issues/102), unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?
> 
> And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.

Yes agree. Sorry @Phil91  we need another extract since the 2 rows have changed.
Details:
image

**Comment by Phil91** [comment]
> as part of [eclipse-tractusx/portal-iam#102](https://github.com/eclipse-tractusx/portal-iam/issues/102), unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?
> 
> And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.



> as part of [eclipse-tractusx/portal-iam#102](https://github.com/eclipse-tractusx/portal-iam/issues/102), unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?
> 
> And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.

Updated

**Comment by Phil91** [comment]
> > as part of [eclipse-tractusx/portal-iam#102](https://github.com/eclipse-tractusx/portal-iam/issues/102), unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?
> > And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.
> 
> Yes agree. Sorry @Phil91 we need another extract since the 2 rows have changed. Details: image
> 
> Please share the IAM PR (as soon as available) with me as well. Thanks!



> > as part of [eclipse-tractusx/portal-iam#102](https://github.com/eclipse-tractusx/portal-iam/issues/102), unfortunately there were still needed to be done some changes. @jjeroch could you please give the your confirmation that there should be done another extract?
> > And this page https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md needs to get updated as well.
> 
> Yes agree. Sorry @Phil91 we need another extract since the 2 rows have changed. Details: image
> 
> Please share the IAM PR (as soon as available) with me as well. Thanks!

It's linked in the ticket description

**Review by evegufy — APPROVED** [review]

**Pull request merged**
