### PR TITLE
docs(developer): registration process enhancement by incl. status endpoint

### PR DESCRIPTION
**Pull request by jjeroch**
## Description

Updated registration details for status change

## Why

Documentation enhancement

## Issue

#255 

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)

### CODE REVIEW

**Comment by evegufy** [comment]
reopen

**Comment by jjeroch** [comment]
@Phil91  I dont have the needed rights to solve the conflict. Can you please have a short look at it - maybe we can solve it easily.

**Comment by Phil91** [comment]
> @Phil91 I dont have the needed rights to solve the conflict. Can you please have a short look at it - maybe we can solve it easily.

I'll take over

**Comment by Phil91** [comment]
> @Phil91 I dont have the needed rights to solve the conflict. Can you please have a short look at it - maybe we can solve it easily.

@jjeroch conflict is resolved.

**Review by Phil91 — APPROVED** [review]

**Pull request merged**
