### PR TITLE
Enhance/company role change documentation

### PR DESCRIPTION
**Pull request by jjeroch**
## Description

Update company role change description.

## Why

Default text removed and individual text values added

## Issue

n/a

## Checklist

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by jjeroch** [comment]
@nidhigarg-bmw  please review the json structure to ensure that we don't have any structural issue - thanks :)

**Comment by nidhigarg-bmw** [comment]
@jjeroch  Why you removed "features" from "ACTIVE_PARTICIPANT" ?

**Comment by nidhigarg-bmw** [comment]
> @jjeroch Why you removed "features" from "ACTIVE_PARTICIPANT" ?

@jjeroch Why you removed "features" from "ACTIVE_PARTICIPANT" ?

**Comment by nidhigarg-bmw** [comment]
> @nidhigarg-bmw please review the json structure to ensure that we don't have any structural issue - thanks :)

@jjeroch Why you removed "features" from "ACTIVE_PARTICIPANT" ?

**Review by Phil91 — DISMISSED** [review]

**Review by oyo — APPROVED** [review]

**Pull request merged**
