### PR TITLE
fix(standard library): add std library template

### PR DESCRIPTION
**Pull request by manojava-gk**
## Description

add std library template information to the sections under company roles

## Why

std library information should be present in all the sections of company roles

## Issue

NA

## Checklist

Please delete options that are not relevant.

- [x] I have followed the [contributing guidelines](https://github.com/eclipse-tractusx/portal-assets/blob/main/developer/Technical%20Documentation/Dev%20Process/How%20to%20contribute.md#commit-and-pr-guidelines)
- [ ] I have performed [IP checks](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04#checking-libraries-using-the-eclipse-dash-license-tool) for added or updated 3rd party libraries
- [ ] I have created and linked IP issues or requested their creation by a committer
- [ ] I have added copyright and license headers, footers (for .md files) or files (for images)
- [x] I have performed a self-review of my own code
- [x] I have successfully tested my changes locally
- [ ] I have added tests that prove my changes work
- [ ] I have checked that new and existing tests pass locally with my changes
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by manojava-gk** [comment]
@evegufy Any reason to close it?

**Comment by evegufy** [comment]
> @evegufy Any reason to close it?

@manojava-gk it was closed automatically, when I merged the branch into main and the branch got deleted, I'm reopening the PR.

**Comment by evegufy** [comment]
Reopen

**Comment by evegufy** [comment]
reopen

**Comment by manojava-gk** [comment]
> reopen

Ok. Thanks

**Review by oyo — APPROVED** [review]

**Pull request merged**
